apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lk28fcpza-go 
  janus-idp.io/tekton: lk28fcpza-go
  backstage.io/kubernetes-id: lk28fcpza-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lk28fcpza-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml