apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lk28fcpza-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lk28fcpza-go 
  name: lk28fcpza-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lk28fcpza-go 
